<?php
 if( function_exists('acf_add_local_field_group') ):

 acf_add_local_field_group(array(
  'key' => 'group_57de1186a9abb',
  'title' => 'Portfolio',
  'fields' => array(
   array(
    'key' => 'field_57de118e1dff9',
    'label' => 'Websites',
    'name' => 'websites',
    'type' => 'repeater',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'collapsed' => '',
    'min' => 0,
    'max' => 0,
    'layout' => 'table',
    'button_label' => 'Add Row',
    'sub_fields' => array(
     array(
      'key' => 'field_57de11a31dffa',
      'label' => 'Title',
      'name' => 'title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
     ),
     array(
      'key' => 'field_57de11af1dffb',
      'label' => 'Site URL',
      'name' => 'site_url',
      'type' => 'url',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
     ),
     array(
      'key' => 'field_57de11c91dffc',
      'label' => 'Thumbnail',
      'name' => 'thumbnail',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
     ),
     array(
      'key' => 'field_57de11f01dffd',
      'label' => 'Description',
      'name' => 'description',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'delay' => 0,
     ),
    ),
   ),
  ),
  'location' => array(
   array(
    array(
     'param' => 'page_template',
     'operator' => '==',
     'value' => 'portfolio.php',
    ),
   ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
 ));

 acf_add_local_field_group(array(
  'key' => 'group_60e7c5ebb389f',
  'title' => 'Single Post',
  'fields' => array(
   array(
    'key' => 'field_60e7c60180bd3',
    'label' => 'Single Post',
    'name' => 'single-post',
    'type' => 'post_object',
    'instructions' => '',
    'required' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'post_type' => '',
    'taxonomy' => '',
    'allow_null' => 0,
    'multiple' => 0,
    'return_format' => 'object',
    'ui' => 1,
   ),
   array(
    'key' => 'field_60e92178d2227',
    'label' => 'Single Post ID',
    'name' => 'single_post_id',
    'type' => 'text',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
   ),
  ),
  'location' => array(
   array(
    array(
     'param' => 'block',
     'operator' => '==',
     'value' => 'acf/blog-post',
    ),
   ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
 ));

 endif;
?>
