<?php
 if( function_exists('acf_add_local_field_group') ):

 acf_add_local_field_group(array(
  'key' => 'group_57de1186a9abb',
  'title' => 'Portfolio',
  'fields' => array(
   array(
    'key' => 'field_57de118e1dff9',
    'label' => 'Websites',
    'name' => 'websites',
    'type' => 'repeater',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'collapsed' => '',
    'min' => 0,
    'max' => 0,
    'layout' => 'table',
    'button_label' => 'Add Row',
    'sub_fields' => array(
     array(
      'key' => 'field_57de11a31dffa',
      'label' => 'Title',
      'name' => 'title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
     ),
     array(
      'key' => 'field_57de11af1dffb',
      'label' => 'Site URL',
      'name' => 'site_url',
      'type' => 'url',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
     ),
     array(
      'key' => 'field_57de11c91dffc',
      'label' => 'Thumbnail',
      'name' => 'thumbnail',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
     ),
     array(
      'key' => 'field_57de11f01dffd',
      'label' => 'Description',
      'name' => 'description',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'delay' => 0,
     ),
    ),
   ),
  ),
  'location' => array(
   array(
    array(
     'param' => 'page_template',
     'operator' => '==',
     'value' => 'portfolio.php',
    ),
   ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
 ));

 acf_add_local_field_group(array(
  'key' => 'group_580bc4d85e9a7',
  'title' => 'Resume',
  'fields' => array(
   array(
    'key' => 'field_580bc4ddb730c',
    'label' => 'Resume Section',
    'name' => 'resume_section',
    'type' => 'repeater',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
     'width' => '',
     'class' => '',
     'id' => '',
    ),
    'collapsed' => '',
    'min' => 0,
    'max' => 0,
    'layout' => 'row',
    'button_label' => 'Add Row',
    'sub_fields' => array(
     array(
      'key' => 'field_580bc4ecb730d',
      'label' => 'Section Title',
      'name' => 'section_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
     ),
     array(
      'key' => 'field_580c46cc2a60f',
      'label' => 'Has Description',
      'name' => 'has_description',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
     ),
     array(
      'key' => 'field_580bc530b730e',
      'label' => 'Section Description',
      'name' => 'section_content',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
       array(
        array(
         'field' => 'field_580c46cc2a60f',
         'operator' => '==',
         'value' => '1',
        ),
       ),
      ),
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'delay' => 0,
     ),
     array(
      'key' => 'field_580c3d5b53e21',
      'label' => 'Resume Items',
      'name' => 'resume_items',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
       'width' => '',
       'class' => '',
       'id' => '',
      ),
      'collapsed' => '',
      'min' => 0,
      'max' => 0,
      'layout' => 'row',
      'button_label' => 'Add Row',
      'sub_fields' => array(
       array(
        'key' => 'field_580c3d7d53e22',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
         'width' => '',
         'class' => '',
         'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
       ),
       array(
        'key' => 'field_580c3d8853e23',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
         'width' => '',
         'class' => '',
         'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
       ),
       array(
        'key' => 'field_580c3d9953e24',
        'label' => 'Date',
        'name' => 'date',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
         'width' => '',
         'class' => '',
         'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
       ),
      ),
     ),
    ),
   ),
  ),
  'location' => array(
   array(
    array(
     'param' => 'page_template',
     'operator' => '==',
     'value' => 'resume.php',
    ),
   ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
 ));

 endif;
?>
